# SPDX-License-Identifier: MIT-0
---
- name: OpenShift install bastion
  hosts: all
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: cloudflare_dns
      tags: [setup]

    - ansible.builtin.import_role:
        name: setup_clis
      tags: [setup]

    - ansible.builtin.include_role:
        name: openshift_configs
        tasks_from: setup_configs.yml
      tags: [setup, destroy]

    - ansible.builtin.include_role:
        name: openshift_libvirt
      vars:
        openshift_libvirt_coreos_qcow2_gz_location: "{{ openshift_configs_coreos_qcow2_gz_location }}"
        openshift_libvirt_coreos_qcow2_gz_sha256: "{{ openshift_configs_coreos_qcow2_gz_sha256 }}"
        openshift_libvirt_bootstrap_ign_path: "{{ openshift_configs_bootstrap_ign_path }}"
        openshift_libvirt_master_ign_path: "{{ openshift_configs_master_ign_path }}"
        openshift_libvirt_worker_ign_path: "{{ openshift_configs_worker_ign_path }}"
      tags: [setup, destroy]

    - ansible.builtin.include_role:
        name: openshift_configs
        tasks_from: wait_for_bootstrap_complete.yml
      tags: [setup]

    - ansible.builtin.include_role:
        name: openshift_libvirt
      tags: [destroy_bootstrap]

    - ansible.builtin.include_role:
        name: openshift_configs
        tasks_from: wait_for_installation.yml
      tags: [destroy_bootstrap]

