# SPDX-License-Identifier: MIT-0
---
- import_playbook: opnsense_setup.yml

- name: Undefine all libvirt domains (delete VM disks), remove configured networks
  hosts: all
  become: true
  tasks:
    - name: Tear down libvirt guests and networks
      ansible.builtin.include_role:
        name: libvirt_emtpy_host
        apply:
          tags:
            - destroy
      tags: [never, destroy]
