# SPDX-License-Identifier: MIT-0
---
- name: asserts | openshift_install.openshift_libvirt
  ansible.builtin.include_tasks: asserts.yml

- name: network | openshift_install.openshift_libvirt
  ansible.builtin.include_tasks: network.yml

- name: firewall | openshift_install.openshift_libvirt
  ansible.builtin.include_tasks: firewall.yml

- name: haproxy | openshift_install.openshift_libvirt
  ansible.builtin.include_tasks: haproxy.yml

- name: nodes | openshift_install.openshift_libvirt
  ansible.builtin.include_tasks: nodes.yml
