# SPDX-License-Identifier: MIT-0
---
- name: Provision Opnsense setup
  import_playbook: opnsense_setup.yml

- name: Undefine all libvirt domains (delete VM disks), remove configured networks
  hosts: all
  become: true
  tasks:
    - name: Remove all firewalld DNAT forward-ports in public zone | destroy
      ansible.builtin.include_role:
        name: firewalld_mgt
        apply:
          tags:
            - destroy
      vars:
        firewalld_mgmt_type: destination_nat_purge
        firewalld_mgmt_zone: public
      tags: [never, destroy]

    - name: Remove source NAT for OPEN lab bridge hvopen0 (if present) | destroy
      ansible.builtin.include_role:
        name: firewalld_mgt
        apply:
          tags:
            - destroy
      vars:
        firewalld_mgmt_mode: absent
        firewalld_mgmt_type: source_nat
        firewalld_mgmt_source_nat_interface: hvopen0
        firewalld_mgmt_source_nat_from_zone: trusted
        firewalld_mgmt_source_nat_to_zone: public
      tags: [never, destroy]

    - name: Remove source NAT for NAT lab bridge hvlab0 (if present) | destroy
      ansible.builtin.include_role:
        name: firewalld_mgt
        apply:
          tags:
            - destroy
      vars:
        firewalld_mgmt_mode: absent
        firewalld_mgmt_type: source_nat
        firewalld_mgmt_source_nat_interface: hvlab0
        firewalld_mgmt_source_nat_from_zone: trusted
        firewalld_mgmt_source_nat_to_zone: public
      tags: [never, destroy]

    - name: Tear down libvirt guests and networks
      ansible.builtin.include_role:
        name: libvirt_emtpy_host
        apply:
          tags:
            - destroy
      tags: [never, destroy]
